# Mapping 43 class chuẩn của GTSRB (German Traffic Sign Recognition Benchmark)
# sang tên tiếng Việt KHÔNG DẤU. Dùng chung cho main.py (demo) và báo cáo.
# Không dấu vì cv2.putText của OpenCV không hỗ trợ hiển thị ký tự Unicode
# có dấu tiếng Việt (sẽ hiện dấu '?' nếu dùng bản có dấu).
# Thứ tự ClassId 0-42 đúng theo cấu trúc thư mục Train/0 .. Train/42 của GTSRB.

CLASS_NAMES = {
    0: "Gioi han toc do (20km/h)",
    1: "Gioi han toc do (30km/h)",
    2: "Gioi han toc do (50km/h)",
    3: "Gioi han toc do (60km/h)",
    4: "Gioi han toc do (70km/h)",
    5: "Gioi han toc do (80km/h)",
    6: "Het gioi han toc do (80km/h)",
    7: "Gioi han toc do (100km/h)",
    8: "Gioi han toc do (120km/h)",
    9: "Cam vuot",
    10: "Cam vuot doi voi xe tren 3.5 tan",
    11: "Giao nhau voi duong uu tien phia truoc",
    12: "Duong uu tien",
    13: "Giao nhau, nhuong duong (Yield)",
    14: "Dung lai (Stop)",
    15: "Duong cam (cam moi loai xe)",
    16: "Cam xe tren 3.5 tan",
    17: "Cam di nguoc chieu",
    18: "Nguy hiem khac, chu y",
    19: "Cho ngoat nguy hiem ben trai",
    20: "Cho ngoat nguy hiem ben phai",
    21: "Hai cho ngoat nguy hiem lien tiep",
    22: "Duong go ghe",
    23: "Duong tron truot",
    24: "Duong hep ben phai",
    25: "Cong truong thi cong",
    26: "Den tin hieu giao thong",
    27: "Duong nguoi di bo cat ngang",
    28: "Tre em qua duong",
    29: "Duong nguoi di xe dap cat ngang",
    30: "Can than tron truot do bang/tuyet",
    31: "Thu rung qua duong",
    32: "Het moi lenh cam",
    33: "Re phai phia truoc",
    34: "Re trai phia truoc",
    35: "Chi di thang",
    36: "Di thang hoac re phai",
    37: "Di thang hoac re trai",
    38: "Di ben phai",
    39: "Di ben trai",
    40: "Noi giao nhau chay theo vong xuyen",
    41: "Het cam vuot",
    42: "Het cam vuot doi voi xe tren 3.5 tan",
}